-- Business Ideas Seed Data (10 Realistic Indian Businesses)
INSERT INTO business_ideas (
  title, slug, category, subcategory, description, 
  investment_min, investment_max, location_type, time_commitment, skill_level,
  monthly_profit_min, monthly_profit_max, pros, cons, required_licenses, required_skills,
  is_trending, is_active, view_count, image_url
) VALUES
('Home-Based Tiffin Service', 'home-based-tiffin-service', 'Food', 'Catering', 'Provide home-cooked, healthy meals to office goers and students in your locality.', 15000, 50000, 'home-based', 'full-time', 'beginner', 25000, 60000, ARRAY['Low starting cost', 'High repeat customer rate', 'Can be managed from home kitchen'], ARRAY['Labor intensive', 'Strict hygiene requirements', 'Delivery logistics can be tricky'], ARRAY['FSSAI Registration', 'Local Municipal Trade License'], ARRAY['Cooking', 'Time Management', 'Basic Accounting'], true, true, 1200, '🍛'),
('Freelance Social Media Management', 'freelance-social-media', 'Services', 'Digital Marketing', 'Manage Instagram, Facebook, and LinkedIn accounts for local small businesses.', 0, 5000, 'online-only', 'flexible', 'intermediate', 20000, 100000, ARRAY['Zero to negligible startup cost', 'Work from anywhere', 'High demand among MSMEs'], ARRAY['Requires constant learning of algorithms', 'Dealing with demanding clients', 'Inconsistent income initially'], ARRAY['GST Registration (if revenue exceeds threshold)'], ARRAY['Content Creation', 'Copywriting', 'Analytics'], true, true, 950, '📱'),
('Handmade Soap Manufacturing', 'handmade-soap-manufacturing', 'Retail', 'Cosmetics', 'Create and sell organic, chemical-free handmade soaps online and through local boutiques.', 10000, 30000, 'home-based', 'part-time', 'beginner', 15000, 45000, ARRAY['High profit margins', 'Creative expression', 'Growing organic market in India'], ARRAY['Crowded online market', 'Shelf-life considerations', 'Requires batch testing'], ARRAY['Cosmetic Manufacturing License (State FDA)', 'MSME Udyam Registration', 'GST Registration'], ARRAY['Basic Chemistry', 'Packaging', 'Online Marketing'], false, true, 450, '🧼'),
('Local SEO Agency', 'local-seo-agency', 'Technology', 'Marketing', 'Help local businesses rank higher on Google Maps and local search results.', 5000, 20000, 'online-only', 'flexible', 'advanced', 30000, 150000, ARRAY['Recurring monthly revenue', 'Scalable with freelancers', 'High ROI for clients'], ARRAY['Results take time to show', 'Google algorithm updates can disrupt rankings', 'Client education required'], ARRAY['GST Registration', 'MSME Registration'], ARRAY['SEO Knowledge', 'Client Servicing', 'Sales'], true, true, 800, '💻'),
('Boutique Tea Stall (Chai Tapri)', 'boutique-tea-stall', 'Food', 'Beverages', 'A modern, hygienic take on the traditional Indian chai tapri serving flavored teas and snacks.', 50000, 200000, 'physical-shop', 'full-time', 'beginner', 40000, 120000, ARRAY['Extremely high volume potential', 'Low cost per product', 'Cultural staple in India'], ARRAY['Requires prime physical location', 'Long working hours', 'Staff retention issues'], ARRAY['FSSAI License', 'Trade License', 'Fire Safety NOC'], ARRAY['Customer Service', 'Inventory Management'], true, true, 1500, '☕'),
('Online Tutoring (Regional Languages)', 'online-tutoring', 'Education', 'E-Learning', 'Teach subjects to school students using their native regional language (Hindi, Marathi, Tamil, etc.).', 2000, 15000, 'online-only', 'part-time', 'intermediate', 15000, 50000, ARRAY['Zero commute', 'Flexible timings', 'Huge tier-2/tier-3 demand'], ARRAY['Internet dependency', 'Building initial student base takes time'], ARRAY[], ARRAY['Subject Matter Expertise', 'Patience', 'Basic Tech Savviness'], false, true, 600, '📚'),
('Dropshipping E-commerce', 'dropshipping-ecommerce', 'Retail', 'Online Retail', 'Sell trending products online without holding inventory. Suppliers ship directly to customers.', 20000, 100000, 'online-only', 'flexible', 'advanced', 20000, 200000, ARRAY['No inventory risk', 'Location independent', 'Easy to test products'], ARRAY['Low profit margins', 'Highly competitive', 'Dependency on suppliers for quality'], ARRAY['GST Registration', 'Current Bank Account'], ARRAY['Digital Marketing (FB/Insta Ads)', 'Website Design', 'Customer Support'], true, true, 1100, '🛒'),
('Cloud Kitchen (Biryani)', 'cloud-kitchen-biryani', 'Food', 'Restaurant', 'A delivery-only kitchen specializing in regional Biryani varieties listed on Swiggy/Zomato.', 200000, 500000, 'hybrid', 'full-time', 'intermediate', 50000, 250000, ARRAY['Lower rent than dine-in', 'Data-driven menus', 'Scalable across cities'], ARRAY['High commission to delivery apps', 'Heavy reliance on online ratings', 'High initial setup cost'], ARRAY['FSSAI State License', 'GST Registration', 'Fire NOC', 'Trade License'], ARRAY['Standardized Cooking', 'Supply Chain Management'], true, true, 1800, '🍗'),
('Corporate Gifting Service', 'corporate-gifting', 'Retail', 'B2B', 'Curate and supply customized gift hampers for corporate events, Diwali, and employee onboarding.', 50000, 150000, 'home-based', 'flexible', 'intermediate', 30000, 150000, ARRAY['High ticket size per order', 'B2B repeat business', 'Excellent margins during festivals'], ARRAY['Highly seasonal', 'Working capital required for bulk orders', 'Logistics management'], ARRAY['GST Registration', 'MSME Udyam'], ARRAY['Networking', 'Procurement', 'Packaging Design'], false, true, 550, '🎁'),
('Yoga & Wellness Studio', 'yoga-wellness-studio', 'Health', 'Fitness', 'A boutique studio offering group yoga classes, meditation sessions, and wellness workshops.', 200000, 600000, 'physical-shop', 'full-time', 'advanced', 40000, 150000, ARRAY['High client retention', 'Positive community impact', 'Premium pricing possible'], ARRAY['High real estate costs', 'Requires certified instructors', 'Space constraints limit scalability'], ARRAY['Trade License', 'Shops and Establishment Registration'], ARRAY['Yoga Certification', 'Community Building', 'Marketing'], false, true, 700, '🧘');
