export type BusinessIdea = {
  id: number;
  title: string;
  slug: string;
  category: 'Food' | 'Education' | 'Technology' | 'Services' | 'Retail' | 'Manufacturing' | 'Agriculture' | 'Health' | 'Fashion' | 'Transportation';
  subcategory: string | null;
  description: string;
  investment_min: number;
  investment_max: number;
  location_type: 'home-based' | 'physical-shop' | 'online-only' | 'hybrid';
  time_commitment: 'part-time' | 'full-time' | 'flexible' | null;
  skill_level: 'beginner' | 'intermediate' | 'advanced' | null;
  monthly_profit_min: number | null;
  monthly_profit_max: number | null;
  pros: string[];
  cons: string[];
  required_licenses: string[];
  required_skills: string[];
  real_example_name: string | null;
  real_example_location: string | null;
  real_example_description: string | null;
  market_size_note: string | null;
  competition_level: 'low' | 'medium' | 'high' | null;
  image_url: string | null;
  is_trending: boolean;
  is_active: boolean;
  view_count: number;
  market_analysis?: any;
  competition_strategy?: any;
  roadmap?: any;
  financial_projections?: any;
  resources_needed?: string[];
  risk_analysis?: any;
  success_stories?: any;
  created_at: string;
  updated_at: string;
};

export type CommunityIdea = {
  id: number;
  user_id: string | null;
  title: string;
  description: string;
  category: string;
  investment_min: number;
  investment_max: number;
  location_type: string;
  monthly_profit_min: number | null;
  monthly_profit_max: number | null;
  time_commitment: string | null;
  skill_level: string | null;
  pros: string[];
  cons: string[];
  required_skills: string[];
  required_licenses: string[];
  real_example_name: string | null;
  real_example_location: string | null;
  real_example_description: string | null;
  image_url: string | null;
  slug: string | null;
  is_approved: boolean;
  ai_generated: boolean;
  contributor_name: string | null;
  market_analysis: any;
  competition_strategy: any;
  roadmap: any;
  financial_projections: any;
  resources_needed: string[];
  risk_analysis: any;
  success_stories: any;
  view_count: number;
  created_at: string;
  updated_at: string;
};

export type SavedIdea = {
  id: string;
  user_id: string;
  business_idea_id: number;
  note: string | null;
  created_at: string;
};
