export function downloadProfessionalReport(stats: any, filename: string) {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Apna Vyapar - ${filename}</title>
      <style>
         body { font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #1e293b; padding: 50px; background: #fff; max-width: 800px; margin: 0 auto; }
         .header { display: flex; align-items: center; border-bottom: 3px solid #00D4FF; padding-bottom: 25px; margin-bottom: 40px; }
         .logo { width: 60px; height: 60px; background: linear-gradient(135deg, #00D4FF 0%, #0088AA 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center; color: white; font-weight: 900; font-size: 24px; margin-right: 25px; box-shadow: 0 4px 10px rgba(0, 212, 255, 0.3); }
         .title-container { flex: 1; }
         h1 { margin: 0 0 8px 0; color: #0f172a; font-size: 32px; letter-spacing: -0.5px; }
         p.meta { margin: 0; color: #64748b; font-size: 15px; font-weight: 500; }
         h2 { font-size: 20px; color: #334155; margin-bottom: 20px; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px; }
         .stats-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 24px; margin-bottom: 50px; }
         .stat-card { background: #f8fafc; padding: 25px; border-radius: 16px; border: 1px solid #e2e8f0; box-shadow: 0 2px 5px rgba(0,0,0,0.02); }
         .stat-title { font-size: 13px; color: #64748b; text-transform: uppercase; letter-spacing: 1.2px; font-weight: 700; margin-bottom: 8px; display: block; }
         .stat-value { font-size: 36px; color: #0f172a; font-weight: 800; }
         .weekly-table { width: 100%; border-collapse: collapse; margin-bottom: 50px; }
         .weekly-table th { background: #f1f5f9; text-align: left; padding: 12px 15px; font-size: 14px; color: #475569; border-bottom: 2px solid #cbd5e1; }
         .weekly-table td { padding: 12px 15px; border-bottom: 1px solid #e2e8f0; font-size: 15px; color: #1e293b; font-weight: 500; }
         .footer { margin-top: 60px; text-align: center; color: #94a3b8; font-size: 13px; border-top: 1px solid #e2e8f0; padding-top: 30px; line-height: 1.6; }
         .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 120px; color: rgba(0, 212, 255, 0.03); font-weight: 900; z-index: -1; pointer-events: none; white-space: nowrap; }
         
         @media print {
           body { padding: 0; }
           .stat-card { border: 1px solid #cbd5e1; box-shadow: none; }
           -webkit-print-color-adjust: exact;
           print-color-adjust: exact;
         }
      </style>
    </head>
    <body>
      <div class="watermark">APNA VYAPAR</div>
      
      <div class="header">
        <div class="logo">AV</div>
        <div class="title-container">
          <h1>Analytics Overview Report</h1>
          <p class="meta">Generated by <strong>Apna Vyapar</strong> • ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>
        </div>
      </div>
      
      <h2>Performance Summary</h2>
      <div class="stats-grid">
        <div class="stat-card">
          <span class="stat-title">Total Revenue</span>
          <div class="stat-value">₹${stats.revenue.toLocaleString('en-IN')}</div>
        </div>
        <div class="stat-card">
          <span class="stat-title">Total Orders</span>
          <div class="stat-value">${stats.orders}</div>
        </div>
        <div class="stat-card">
          <span class="stat-title">Active Customers</span>
          <div class="stat-value">${stats.customers}</div>
        </div>
        <div class="stat-card">
          <span class="stat-title">Conversion Rate</span>
          <div class="stat-value">${stats.orders > 0 ? "3.2%" : "0%"}</div>
        </div>
      </div>
      
      <h2>Weekly Breakdown (Last 4 Weeks)</h2>
      <table class="weekly-table">
        <thead>
          <tr>
            <th>Time Period</th>
            <th>Revenue Generated</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Week 1 (Oldest)</td>
            <td>₹${(stats.weeklyRevenue?.[0] || 0).toLocaleString('en-IN')}</td>
          </tr>
          <tr>
            <td>Week 2</td>
            <td>₹${(stats.weeklyRevenue?.[1] || 0).toLocaleString('en-IN')}</td>
          </tr>
          <tr>
            <td>Week 3</td>
            <td>₹${(stats.weeklyRevenue?.[2] || 0).toLocaleString('en-IN')}</td>
          </tr>
          <tr>
            <td>Week 4 (Current)</td>
            <td>₹${(stats.weeklyRevenue?.[3] || 0).toLocaleString('en-IN')}</td>
          </tr>
        </tbody>
      </table>
      
      <div class="footer">
        <p>This professional report was automatically generated by <strong>Apna Vyapar</strong> platform.</p>
        <p><strong>Apna Vyapar</strong> - Empowering Your Business, Digitally Transformed.</p>
        <p style="margin-top: 15px; font-size: 11px; color: #cbd5e1;">CONFIDENTIAL DOCUMENT</p>
      </div>
      
      <script>
        // Automatically trigger print dialog when opened
        window.onload = () => {
          setTimeout(() => {
             window.print();
          }, 500);
        };
      </script>
    </body>
    </html>
  `;
  
  const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  
  // Open the report in a new tab which will auto-print
  window.open(url, '_blank');
}
